services:
#    parser.example:
#        class: ParserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    one.steam.parser:
        class: ParserBundle\Service\OneSteamParser
        public: true
        arguments:
            $manager: '@doctrine.orm.default_entity_manager'
    multi.steam.parser:
        class: ParserBundle\Service\MultiSteamParser
        public: true
        arguments:
            $manager: '@doctrine.orm.default_entity_manager'
